yahoo_finance_tickers = {
    'Cipla Ltd (L)': 'CIPLA.NS',
    'Adani Enterprises Ltd (L)': 'ADANIENT.NS',
    'Divis Laboratories Ltd (L)': 'DIVISLAB.NS',
    'Hindalco Industries Ltd (L)': 'HINDALCO.NS',
    'Axis Bank Ltd (L)': 'AXISBANK.NS',
    'JSW Steel Ltd (L)': 'JSWSTEEL.NS',
    'HDFC Bank Ltd (L)': 'HDFCBANK.NS',
    'ICICI Bank Ltd (L)': 'ICICIBANK.NS',
    'HDFC Life Insurance Company Ltd (L)': 'HDFCLIFE.NS',
    'NTPC Ltd (L)': 'NTPC.NS',
    'Asian Paints Ltd (L)': 'ASIANPAINT.NS',
    'Mahindra & Mahindra Ltd (L)': 'M&M.NS',
    'Adani Ports and Special Economic Zone Ltd (L)': 'ADANIPORTS.NS',
    'Kotak Mahindra Bank Ltd (L)': 'KOTAKBANK.NS',
    'Maruti Suzuki India Ltd (L)': 'MARUTI.NS',
    'Larsen & Toubro Ltd (L)': 'LT.NS',
    'Bajaj Auto Ltd (L)': 'BAJAJ-AUTO.NS',
    'State Bank Of India (L)': 'SBIN.NS',
    'LTIMindtree Ltd (L)': 'MINDTREE.NS',
    'Dr. Reddys Laboratories Ltd (L)': 'DRREDDY.NS',
    'Reliance Industries Ltd (L)': 'RELIANCE.NS',
    'Power Grid Corporation Of India Ltd (L)': 'POWERGRID.NS',
    'Sun Pharmaceutical Industries Ltd (L)': 'SUNPHARMA.NS',
    'SBI Life Insurance Company Ltd (L)': 'SBILIFE.NS',
    'Hindustan Unilever Ltd (L)': 'HINDUNILVR.NS',
    'Bharat Petroleum Corporation Ltd (L)': 'BPCL.NS',
    'Titan Company Ltd (L)': 'TITAN.NS',
    'Grasim Industries Ltd (L)': 'GRASIM.NS',
    'Bajaj Finserv Ltd (L)': 'BAJAJFINSV.NS',
    'Bharti Airtel Ltd (L)': 'BHARTIARTL.NS',
    'Coal India Ltd (L)': 'COALINDIA.NS',
    'Tata Consumer Products Ltd (L)': 'TATACONSUM.NS',
    'ITC Ltd (L)': 'ITC.NS',
    'Hero MotoCorp Ltd (M)': 'HEROMOTOCO.NS',
    'Tata Steel Ltd (L)': 'TATASTEEL.NS',
    'Bajaj Finance Ltd (L)': 'BAJFINANCE.NS',
    'Ultratech Cement Ltd (L)': 'ULTRACEMCO.NS',
    'IndusInd Bank Ltd (L)': 'INDUSINDBK.NS',
    'Infosys Ltd (L)': 'INFY.NS',
    'Eicher Motors Ltd (L)': 'EICHERMOT.NS',
    'Tata Motors Ltd (L)': 'TATAMOTORS.NS',
    'Oil & Natural Gas Corporation Ltd (L)': 'ONGC.NS',
    'Tech Mahindra Ltd (L)': 'TECHM.NS',
    'Nestle India Ltd (L)': 'NESTLEIND.NS',
    'UPL Ltd (M)': 'UPL.NS',
    'Britannia Industries Ltd (L)': 'BRITANNIA.NS',
    'Tata Consultancy Services Ltd (L)': 'TCS.NS',
    'Wipro Ltd (L)': 'WIPRO.NS',
    'HCL Technologies Ltd (L)': 'HCLTECH.NS',
    'Apollo Hospitals Enterprise Ltd (L)': 'APOLLOHOSP.NS',
}
